function Foo()
    if X1 == 0 then --[[ do something ]] end
    if X2 == 0 then --[[ do something ]] end
    if X3 == 0 then --[[ do something ]] end
    if X4 == 0 then --[[ do something ]] end
    if X5 == 0 then --[[ do something ]] end
    if X6 == 0 then --[[ do something ]] end
    if X7 == 0 then --[[ do something ]] end
    if X8 == 0 then --[[ do something ]] end
    if X9 == 0 then --[[ do something ]] end
    if X10 == 0 then --[[ do something ]] end
    if X11 == 0 then --[[ do something ]] end
    if X12 == 0 then --[[ do something ]] end
    if X13 == 0 then --[[ do something ]] end
    if X14 == 0 then --[[ do something ]] end
    if X15 == 0 then --[[ do something ]] end
    if X16 == 0 then --[[ do something ]] end
    if X17 == 0 then --[[ do something ]] end
    if X18 == 0 then --[[ do something ]] end
    if X19 == 0 then --[[ do something ]] end
    if X20 == 0 then --[[ do something ]] end
    if X21 == 0 then --[[ do something ]] end
    if X22 == 0 then --[[ do something ]] end
    if X23 == 0 then --[[ do something ]] end
    if X24 == 0 then --[[ do something ]] end
    if X25 == 0 then --[[ do something ]] end
    if X26 == 0 then --[[ do something ]] end
    if X27 == 0 then --[[ do something ]] end
    if X28 == 0 then --[[ do something ]] end
    if X29 == 0 then --[[ do something ]] end
    if X30 == 0 then --[[ do something ]] end
    if X31 == 0 then --[[ do something ]] end
    if X32 == 0 then --[[ do something ]] end
    if X33 == 0 then --[[ do something ]] end
    if X34 == 0 then --[[ do something ]] end
    if X35 == 0 then --[[ do something ]] end
    if X36 == 0 then --[[ do something ]] end
    if X37 == 0 then --[[ do something ]] end
    if X38 == 0 then --[[ do something ]] end
    if X39 == 0 then --[[ do something ]] end
    if X40 == 0 then --[[ do something ]] end
    if X41 == 0 then --[[ do something ]] end
    if X42 == 0 then --[[ do something ]] end
    if X43 == 0 then --[[ do something ]] end
    if X44 == 0 then --[[ do something ]] end
    if X45 == 0 then --[[ do something ]] end
    if X46 == 0 then --[[ do something ]] end
    if X47 == 0 then --[[ do something ]] end
    if X48 == 0 then --[[ do something ]] end
    if X49 == 0 then --[[ do something ]] end
    if X50 == 0 then --[[ do something ]] end
    if X51 == 0 then --[[ do something ]] end
    if X52 == 0 then --[[ do something ]] end
    if X53 == 0 then --[[ do something ]] end
    if X54 == 0 then --[[ do something ]] end
    if X55 == 0 then --[[ do something ]] end
    if X56 == 0 then --[[ do something ]] end
    if X57 == 0 then --[[ do something ]] end
    if X58 == 0 then --[[ do something ]] end
    if X59 == 0 then --[[ do something ]] end
    if X60 == 0 then --[[ do something ]] end
    if X61 == 0 then --[[ do something ]] end
    if X62 == 0 then --[[ do something ]] end
    if X63 == 0 then --[[ do something ]] end
    if X64 == 0 then --[[ do something ]] end
    if X65 == 0 then --[[ do something ]] end
    if X66 == 0 then --[[ do something ]] end
    if X67 == 0 then --[[ do something ]] end
    if X68 == 0 then --[[ do something ]] end
    if X69 == 0 then --[[ do something ]] end
    if X70 == 0 then --[[ do something ]] end
    if X71 == 0 then --[[ do something ]] end
    if X72 == 0 then --[[ do something ]] end
    if X73 == 0 then --[[ do something ]] end
    if X74 == 0 then --[[ do something ]] end
    if X75 == 0 then --[[ do something ]] end
    if X76 == 0 then --[[ do something ]] end
    if X77 == 0 then --[[ do something ]] end
    if X78 == 0 then --[[ do something ]] end
    if X79 == 0 then --[[ do something ]] end
    if X80 == 0 then --[[ do something ]] end
    if X81 == 0 then --[[ do something ]] end
    if X82 == 0 then --[[ do something ]] end
    if X83 == 0 then --[[ do something ]] end
    if X84 == 0 then --[[ do something ]] end
    if X85 == 0 then --[[ do something ]] end
    if X86 == 0 then --[[ do something ]] end
    if X87 == 0 then --[[ do something ]] end
    if X88 == 0 then --[[ do something ]] end
    if X89 == 0 then --[[ do something ]] end
    if X90 == 0 then --[[ do something ]] end
    if X91 == 0 then --[[ do something ]] end
    if X92 == 0 then --[[ do something ]] end
    if X93 == 0 then --[[ do something ]] end
    if X94 == 0 then --[[ do something ]] end
    if X95 == 0 then --[[ do something ]] end
    if X96 == 0 then --[[ do something ]] end
    if X97 == 0 then --[[ do something ]] end
    if X98 == 0 then --[[ do something ]] end
    if X99 == 0 then --[[ do something ]] end
    if X100 == 0 then --[[ do something ]] end
end

